version: '3'
services:
  nextcloudpi:
    image: ownyourbits/nextcloudpi-armhf
    command: "nextcloud.thomasmtran.me"
    ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - ncdata:/data
    container_name: nextcloudpi

volumes:
  ncdata:
